version: 2
updates:
  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: /packages/eslint
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: /packages/prettier
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: /packages/stylelint
    schedule:
      interval: "daily"
