name: publish

on:
  push:
    branches:
      - main
  # release:
  #   types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
         # pulls all commits (needed for lerna / semantic release to correctly version)
         fetch-depth: "0"
      # pulls all tags (needed for lerna / semantic release to correctly version)
      - name: Fetch Updates
        run: git fetch --prune --tags
      - name: Read node version
        run: echo ::set-output name=nodever::$(cat .node-version)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.nodever }}'
          registry-url: https://registry.npmjs.org
      - name: Configure Git User
        run: |
          git config --global user.email "gitlab@roman-minchyn.de"
          git config --global user.name "Roman Minchyn (lerna-bot)"
      - name: Publish with Lerna
        run: npx lerna publish --conventional-commits --yes --no-verify-access
